[package]
name = "workpool"
version = "0.1.0"
authors = ["Glenn Griffin <ggriffiniii@gmail.com>"]

[dependencies]
crossbeam-channel = "0.2.6"
published_value = { git = "https://github.com/ggriffiniii/published_value.git" }
